---
- name: 为系统设置时钟同步
  hosts: centossrvs
  # 定义变量
  vars:                           
    ntp_srv: server ntp1.aliyun.com    # NTP服务器地址使用阿里云的
  # 定义任务
  tasks:
  - name: 设置时区
    community.general.timezone:
      name: Asia/Shanghai
  - name: 安装chrony
    ansible.builtin.yum:
      name: chrony
      state: present
  - name: 设置时钟同步源
    ansible.builtin.lineinfile:
      dest: /etc/chrony.conf
      regexp: 'centos.pool.ntp.org'
      line: '{{ ntp_srv }}'
    notify:
      - restart chrony                  # 通知重启chrony
  # 定义处理程序
  handlers:
    - name: restart chrony
      ansible.builtin.service:
        name: chronyd
        state: restarted
        enabled: yes                    # 开机自动启动


